{
	"version":"LAYASCENE3D:02",
	"data":{
		"type":"Scene3D",
		"props":{
			"name":"main",
			"ambientColor":[
				0.212,
				0.227,
				0.259
			],
			"reflectionDecodingFormat":1,
			"reflection":"Assets/mainGIReflection.ltcb.ls",
			"reflectionIntensity":1,
			"ambientMode":1,
			"ambientSphericalHarmonics":[
				0.1709516,
				-0.01386549,
				-0.008819424,
				0.004114223,
				0.002958511,
				-0.006344575,
				0.01391783,
				-0.0185973,
				0.02635119,
				0.2123266,
				0.0287956,
				-0.01472148,
				0.006865352,
				0.004950067,
				-0.01061669,
				0.02011644,
				-0.02773572,
				0.03731835,
				0.2772378,
				0.1044927,
				-0.02671293,
				0.01246294,
				0.009320222,
				-0.01999003,
				0.02593468,
				-0.03978271,
				0.04459958
			],
			"ambientSphericalHarmonicsIntensity":1,
			"lightmaps":[],
			"enableFog":false,
			"fogStart":0,
			"fogRange":300,
			"fogColor":[
				0.5,
				0.5,
				0.5
			]
		},
		"child":[
			{
				"type":"Camera",
				"instanceID":0,
				"props":{
					"name":"Main Camera",
					"active":true,
					"isStatic":false,
					"layer":0,
					"position":[
						0,
						3,
						-12
					],
					"rotation":[
						0,
						0.9945219,
						0.1045285,
						0
					],
					"scale":[
						1,
						1,
						1
					],
					"clearFlag":0,
					"orthographic":true,
					"orthographicVerticalSize":4.8,
					"fieldOfView":30,
					"enableHDR":true,
					"nearPlane":0.3,
					"farPlane":1000,
					"viewport":[
						0,
						0,
						1,
						1
					],
					"clearColor":[
						0.03297437,
						0.1329759,
						0.1792453,
						0
					]
				},
				"components":[],
				"child":[]
			},
			{
				"type":"DirectionLight",
				"instanceID":1,
				"props":{
					"name":"Directional Light",
					"active":true,
					"isStatic":false,
					"layer":0,
					"position":[
						0,
						2,
						-10
					],
					"rotation":[
						-0.04129865,
						-0.9583586,
						-0.186286,
						0.2124633
					],
					"scale":[
						1,
						1,
						1
					],
					"intensity":1,
					"lightmapBakedType":0,
					"color":[
						0.9245283,
						0.8998161,
						0.8503916
					]
				},
				"components":[],
				"child":[]
			},
			{
				"type":"Sprite3D",
				"instanceID":2,
				"props":{
					"name":"mojie_compound",
					"active":true,
					"isStatic":false,
					"layer":0,
					"position":[
						0,
						-0.3,
						0
					],
					"rotation":[
						0,
						1,
						0,
						0
					],
					"scale":[
						1.1,
						1.1,
						1.1
					]
				},
				"components":[],
				"child":[
					{
						"type":"MeshSprite3D",
						"instanceID":3,
						"props":{
							"name":"mojie_hutui",
							"active":true,
							"isStatic":false,
							"layer":0,
							"position":[
								0,
								0,
								0
							],
							"rotation":[
								0.7071068,
								0,
								0,
								-0.7071068
							],
							"scale":[
								1,
								1,
								1
							],
							"meshPath":"Assets/new_mojie_compound/mojie_compound-mojie_hutui.lm",
							"enableRender":true,
							"receiveShadows":true,
							"castShadow":true,
							"materials":[
								{
									"type":"Laya.BlinnPhongMaterial",
									"path":"Assets/new_mojie_compound/mojie_compound.lmat"
								}
							]
						},
						"components":[],
						"child":[]
					},
					{
						"type":"MeshSprite3D",
						"instanceID":4,
						"props":{
							"name":"mojie_jianjia",
							"active":true,
							"isStatic":false,
							"layer":0,
							"position":[
								0,
								0,
								0
							],
							"rotation":[
								0.7071068,
								0,
								0,
								-0.7071068
							],
							"scale":[
								1,
								1,
								1
							],
							"meshPath":"Assets/new_mojie_compound/mojie_compound-mojie_jianjia.lm",
							"enableRender":true,
							"receiveShadows":true,
							"castShadow":true,
							"materials":[
								{
									"type":"Laya.BlinnPhongMaterial",
									"path":"Assets/new_mojie_compound/mojie_compound.lmat"
								}
							]
						},
						"components":[],
						"child":[]
					},
					{
						"type":"MeshSprite3D",
						"instanceID":5,
						"props":{
							"name":"mojie_luomo",
							"active":true,
							"isStatic":false,
							"layer":0,
							"position":[
								0,
								0,
								0
							],
							"rotation":[
								0.7071068,
								0,
								0,
								-0.7071068
							],
							"scale":[
								1,
								1,
								1
							],
							"meshPath":"Assets/new_mojie_compound/mojie_compound-mojie_luomo.lm",
							"enableRender":true,
							"receiveShadows":true,
							"castShadow":true,
							"materials":[
								{
									"type":"Laya.BlinnPhongMaterial",
									"path":"Assets/new_mojie_compound/mojie_compound.lmat"
								}
							]
						},
						"components":[],
						"child":[]
					},
					{
						"type":"MeshSprite3D",
						"instanceID":6,
						"props":{
							"name":"mojie_shoubi",
							"active":true,
							"isStatic":false,
							"layer":0,
							"position":[
								0,
								0,
								0
							],
							"rotation":[
								0.7071068,
								0,
								0,
								-0.7071068
							],
							"scale":[
								1,
								1,
								1
							],
							"meshPath":"Assets/new_mojie_compound/mojie_compound-mojie_shoubi.lm",
							"enableRender":true,
							"receiveShadows":true,
							"castShadow":true,
							"materials":[
								{
									"type":"Laya.BlinnPhongMaterial",
									"path":"Assets/new_mojie_compound/mojie_compound.lmat"
								}
							]
						},
						"components":[],
						"child":[]
					},
					{
						"type":"MeshSprite3D",
						"instanceID":7,
						"props":{
							"name":"mojie_toukui",
							"active":true,
							"isStatic":false,
							"layer":0,
							"position":[
								0,
								0,
								0
							],
							"rotation":[
								0.7071068,
								0,
								0,
								-0.7071068
							],
							"scale":[
								1,
								1,
								1
							],
							"meshPath":"Assets/new_mojie_compound/mojie_compound-mojie_toukui.lm",
							"enableRender":true,
							"receiveShadows":true,
							"castShadow":true,
							"materials":[
								{
									"type":"Laya.BlinnPhongMaterial",
									"path":"Assets/new_mojie_compound/mojie_compound.lmat"
								}
							]
						},
						"components":[],
						"child":[]
					},
					{
						"type":"MeshSprite3D",
						"instanceID":8,
						"props":{
							"name":"mojie_wuqi",
							"active":true,
							"isStatic":false,
							"layer":0,
							"position":[
								0.9,
								0,
								0.2
							],
							"rotation":[
								0.7071068,
								0,
								0,
								-0.7071068
							],
							"scale":[
								1,
								1,
								1
							],
							"meshPath":"Assets/new_mojie_compound/mojie_compound-mojie_wuqi.lm",
							"enableRender":true,
							"receiveShadows":true,
							"castShadow":true,
							"materials":[
								{
									"type":"Laya.BlinnPhongMaterial",
									"path":"Assets/new_mojie_compound/mojie_compound.lmat"
								}
							]
						},
						"components":[],
						"child":[]
					},
					{
						"type":"MeshSprite3D",
						"instanceID":9,
						"props":{
							"name":"mojie_xiongjia",
							"active":true,
							"isStatic":false,
							"layer":0,
							"position":[
								0,
								0,
								0
							],
							"rotation":[
								0.7071068,
								0,
								0,
								-0.7071068
							],
							"scale":[
								1,
								1,
								1
							],
							"meshPath":"Assets/new_mojie_compound/mojie_compound-mojie_xiongjia.lm",
							"enableRender":true,
							"receiveShadows":true,
							"castShadow":true,
							"materials":[
								{
									"type":"Laya.BlinnPhongMaterial",
									"path":"Assets/new_mojie_compound/mojie_compound.lmat"
								}
							]
						},
						"components":[],
						"child":[]
					},
					{
						"type":"MeshSprite3D",
						"instanceID":10,
						"props":{
							"name":"mojie_yaodai",
							"active":true,
							"isStatic":false,
							"layer":0,
							"position":[
								0,
								0,
								0
							],
							"rotation":[
								0.7071068,
								0,
								0,
								-0.7071068
							],
							"scale":[
								1,
								1,
								1
							],
							"meshPath":"Assets/new_mojie_compound/mojie_compound-mojie_yaodai.lm",
							"enableRender":true,
							"receiveShadows":true,
							"castShadow":true,
							"materials":[
								{
									"type":"Laya.BlinnPhongMaterial",
									"path":"Assets/new_mojie_compound/mojie_compound.lmat"
								}
							]
						},
						"components":[],
						"child":[]
					}
				]
			},
			{
				"type":"Sprite3D",
				"instanceID":11,
				"props":{
					"name":"Canvas",
					"active":true,
					"isStatic":false,
					"layer":5,
					"position":[
						-360,
						640,
						0
					],
					"rotation":[
						0,
						0,
						0,
						-1
					],
					"scale":[
						1,
						1,
						1
					]
				},
				"components":[],
				"child":[
					{
						"type":"Sprite3D",
						"instanceID":12,
						"props":{
							"name":"FPSText",
							"active":true,
							"isStatic":false,
							"layer":5,
							"position":[
								220,
								500,
								0
							],
							"rotation":[
								0,
								0,
								0,
								-1
							],
							"scale":[
								0.5,
								0.5,
								0.5
							]
						},
						"components":[],
						"child":[]
					}
				]
			},
			{
				"type":"MeshSprite3D",
				"instanceID":13,
				"props":{
					"name":"uibackground",
					"active":true,
					"isStatic":false,
					"layer":0,
					"position":[
						0,
						-1.69,
						10
					],
					"rotation":[
						0,
						0,
						0,
						-1
					],
					"scale":[
						2.7,
						4.92,
						1
					],
					"meshPath":"Library/unity default resources-Quad.lm",
					"enableRender":true,
					"receiveShadows":true,
					"castShadow":true,
					"materials":[
						{
							"type":"Laya.BlinnPhongMaterial",
							"path":"Assets/common/uibackground.lmat"
						}
					]
				},
				"components":[
					{
						"type":"PhysicsCollider",
						"restitution":0,
						"friction":0.5,
						"rollingFriction":0,
						"shapes":[
							{
								"type":"MeshColliderShape",
								"mesh":"Library/unity default resources-Quad.lm"
							}
						],
						"isTrigger":false
					}
				],
				"child":[]
			}
		]
	}
}